### ISSUE TITLE
Not compatible with datadog-agent V6

### ISSUE THREAD

**Issue by tpaktop77** [ajclark/datadog-smartmon#4]
```PDT | ERROR | (autoconfig.go:248 in getChecksFromConfigs) | Unable to load the check: unable to load any check from config 'smartmon'```

```
sudo -u dd-agent -- datadog-agent check smartmon

Error: could not load smartmon:
* Core Check Loader: Check smartmon not found in Catalog
* JMX Check Loader: check is not a jmx check, or unable to determine if it's so
* Python Check Loader: ['Traceback (most recent call last):\n', '  File "/etc/datadog-agent/checks.d/smartmon.py", line 1, in <module>\n    from pySMART import DeviceList\n', '  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pySMART/__init__.py", line 108, in <module>\n    from .device import Device, smart_health_assement\n', '  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pySMART/device.py", line 768\n', '    *self.smart_options,\n', '    ^\n', 'SyntaxError: invalid syntax\n']
Error: no valid check found
Usage:
  agent check <check_name> [flags]
```

**Comment by ajclark** [comment]
Hi! Thanks for taking the time to report this and for using my project! 

Unfortunately I cannot reproduce your error using DataDog agent v6. I am using my smartmon plugin successfully with v6. See below:

```
root@nas:~# sudo -u dd-agent -- datadog-agent version
Agent 6.1.4 - Commit: a8ee76d - Serialization version: 4.7

root@nas:~# sudo -u dd-agent -- datadog-agent check smartmon
/opt/datadog-agent/embedded/lib/python2.7/site-packages/pySMART/utils.py:138: UserWarning: _NOT_ADMIN_: smartctl is intended to be run as administrator/root and may not detect all device types, or may parse device information incorrectly, if run without these permissions.
```
## ...snip...
```
    {
      "metric": "smartmon.Spin_Up_Time",
      "points": [
        [
          1524965308,
          5933
        ]
      ],
      "tags": null,
      "host": "nas",
      "device": "sdc",
      "type": "gauge",
      "interval": 0,
      "source_type_name": "System"
    }
  ]
}
=========
Collector
=========

  Running Checks
  ==============
    smartmon
    --------
      Total Runs: 1
      Metrics: 141, Total Metrics: 141
      Events: 0, Total Events: 0
      Service Checks: 0, Total Service Checks: 0
  

Check has run only once, if some metrics are missing you can try again with --check-rate to see any other metric if available.
```

**Comment by tpaktop77** [comment]
Okay, thanks. I didnt really debug that. Probably it is an error like i reported before and it is in pysmart module. I will try to check it deeper. I have more then usually discs. Probably thats why?
